name: Test and Deploy (Functions Core Tooling)

on:
  push:
   branches: [ main ]
   paths-ignore: 
     - '**/README.md'
     - '**/*.yml'
  pull_request:
   branches: [ main ]
  workflow_dispatch:
  
env:
  AZURE_FUNCTIONAPP_NAME: ecommercepostechapp  # set this to the name of your azure function app resource
  AZURE_FUNCTION_PROJ_PATH: src  # set this to the path to your function app project
  ROOT_SOLUTION_PATH: src # set this to the root path of your solution/project file
  DOTNET_VERSION: '7.0.x'
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Authenticate to Azure as a Service Principal
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDS_FUNCTION_APP }}
    
      - name: Get the latest source code commit
        uses: actions/checkout@v2
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Rename build.settings.json to local.settings.json
        run: mv build.settings.json local.settings.json
        working-directory: ${{ env.AZURE_FUNCTION_PROJ_PATH }}
        
      - name: Install Azure Functions Core Tools
        run: npm i -g azure-functions-core-tools@4 --unsafe-perm true
      
      - name: Publish Azure Function App
        run: func azure functionapp publish ${{ env.AZURE_FUNCTIONAPP_NAME }}
        working-directory: ${{ env.AZURE_FUNCTION_PROJ_PATH }}